name: Deploy to Production
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
    
    - name: Deploy to server
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        echo "🚀 Executando deploy no servidor..."
        sshpass -p "$PASSWORD" ssh -p 722 -o StrictHostKeyChecking=no $USERNAME@$HOST "
          cd $DEPLOY_PATH
          git fetch
          git pull
          
          # Criar .env
          echo '🔧 Configurando variáveis de ambiente...'
          echo 'VITE_API_URL=${{ secrets.VITE_API_URL }}' > .env
          echo 'VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}' >> .env
          echo 'NODE_ENV=production' >> .env
          
          # Executar deploy
          ./start_production.sh
          
          # Verificar se container está rodando
          if docker ps | grep -q educar-front-container; then
            echo '✅ Deploy concluído com sucesso!'
          else
            echo '❌ Erro no deploy!'
            exit 1
          fi
        "
